namespace PraktASPApp.Database.Models
{
    public class UsersOdb
    {
        string Users = "-- public.\"Users\" definition\r\n\r\n-- Drop table\r\n\r\n-- DROP TABLE public.\"Users\";\r\n\r\nCREATE TABLE public.\"Users\" (\r\n\t\"Id\" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),\r\n\t\"Login\" text NOT NULL,\r\n\t\"Password\" text NOT NULL,\r\n\t\"FullName\" text NOT NULL,\r\n\tCONSTRAINT \"PK_Users\" PRIMARY KEY (\"Id\")\r\n);";
    }
}
